services:
  vault:
    image: hashicorp/vault:${VAULT_VERSION:-1.15}
    entrypoint: vault server -dev
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_API_ADDR: http://localhost:8200
    ports:
      - 8200:8200
    volumes:
      - vault-data:/vault/file:rw
      - vault-logs:/vault/logs:rw

  localstack:
    image: localstack/localstack:4
    ports:
      - 4566:4566            # LocalStack Gateway
      - 4510-4559:4510-4559  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  vault-data: {}
  vault-logs: {}
  localstack-data: {}
